---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-secret
  namespace: techimera
data:
  PGSQL_USER: cG9zdGdyZXM=
  PGSQL_PASSWORD: cG9zdGdyZXM=
  PGSQL_DATABASE: dGVjaGltZXJh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: techimera
data:
  APP_HOST: 0.0.0.0
  APP_PORT: "9000"
  PGSQL_HOST: postgresql
  PGSQL_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: techimera
spec:
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: luksamuk/techimera:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
            - containerPort: 4005
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          resources:
            requests:
              cpu: 200m
    replicas: 2
    selector:
      matchLabels:
        app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: techimera
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 9000
      nodePort: 30000
    - port: 4005
      nodePort: 31000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: techimera
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
